title: Darius Atmar # your name (or website title) here
logo: "/images/profile-pic-2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist 
  <br><br>
  <a href="https://www.linkedin.com/in/dariusatmar/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-176995351-1 # your Google Analytics tracking ID here
